### PR TITLE
73 about main page

### PR DESCRIPTION
**Pull request by Vladifish**
## Description

- Working about page
- Working about-box component
```javascript
AboutBox props {
  iconURL: string,
  imageURL: string,
  title: string,
  linkURL: string
}

```
- These should both be responsive, but to be double checked nalang

### Desktop page
Screen Shot 2024-08-23 at 13 06 09

### Tablet Page
Screen Shot 2024-08-23 at 13 07 28

### Mobile Page
image
image

## What to watch out for?
- The links should work, but could possibly change depending on how the next few pages are put in the folder structure

### CODE REVIEW

**Comment by JuliaMelle** [comment]
yung mga laman ng iconURL like /assets/GHIBLI ICONS/totoro.png vlad 
hindi na upload sa directory.
image
image

**Comment by Vladifish** [comment]
Just fixed it, added the files na

**Comment by JuliaMelle** [comment]
I think this section is too close to the footer 
image

But overall its okay na and ready to merge

**Comment by scinscinscin** [comment]
Please adjust the ff:
image

 - Header image should span the entire width of the page
 - About text should not be cutoff
 - Body contents should have more spacing against each other
 - The section is too close to the footer
  
See below as reference:
image

**Comment by Vladifish** [comment]
Noted, I'll get to it as soon as I can

**Comment by Vladifish** [comment]
- Fixed the page layout :D
  - Naoverwrite ko pala yung margins dun sa about box section lol
- Also updated repeat header font-size so you should prolly watch out for that  

## Desktop page
image

## Mobile page
image

**Pull request merged**
